// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOGRHdWKOf4W5f9I-bQPaikXUbq_l_K6c',
    appId: '1:299977250009:android:06b3ff2e09946876bb9ac8',
    messagingSenderId: '299977250009',
    projectId: 'dogtalk-83f93',
    databaseURL: 'https://dogtalk-83f93.firebaseio.com',
    storageBucket: 'dogtalk-83f93.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL-6xepKSBYEryv2wyjCtw3fcKLV9vGuo',
    appId: '1:299977250009:ios:acc2b0bba3f132bfbb9ac8',
    messagingSenderId: '299977250009',
    projectId: 'dogtalk-83f93',
    databaseURL: 'https://dogtalk-83f93.firebaseio.com',
    storageBucket: 'dogtalk-83f93.appspot.com',
    androidClientId:
        '299977250009-ecqvpvpu7lfds7k7mre21goeibpg2l3v.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappUi',
  );
}
